- roles/blackbox_exporter/tasks/main.yml
- roles/cassandra/tasks/main.yml
- roles/kubernetes/tasks/main.yml
- roles/kubernetes/templates/networkpolicy-ingress.yml.j2
- roles/kubernetes_common/tasks/coredns.yml
- roles/kubernetes_common/tasks/fluentbit.yml
- roles/kubernetes_common/tasks/ingress.yml
- roles/kubernetes_common/tasks/kubernetes-event-exporter.yml
- roles/kubernetes_common/tasks/main.yml
- roles/kubernetes_common/tasks/monitoring.yml
- roles/kubernetes_common/tasks/nfs-provider.yml
- roles/kubernetes_common/tasks/onepassword.yml
- roles/kubernetes_common/tasks/otc-cert-manager.yml
- roles/kubernetes_common/templates/loki-load-test.yml.j2
- roles/loki/tasks/main.yml
- roles/monitoring_bbb/tasks/main.yml
- roles/multi_instance_onepassword/tasks/multi-instance-onepassword.yml
- roles/multi_instance_onepassword/templates/onepassword-operator-deployment.yml.j2
- roles/resource_pool/tasks/main.yml
- roles/victoriametrics/tasks/main.yml
> OPS-3575 Imported roles from infra-schulcloud ansible

- roles/users/files/sshd_config
update sshd_config to limit tunneluser to tunneling
https://ticketsystem.dbildungscloud.de/browse/OPS-3616
> OPS-3616-create-tunnel-user-for-support2go

- roles/multi_instance_onepassword/tasks/main.yml
> OPS-3644 Fixed multi instance 1Password

- roles/basic/files/motd
- roles/basic/files/sshd_banner.txt
- roles/basic/tasks/configure_motd.yml
- roles/basic/tasks/main.yml
https://ticketsystem.dbildungscloud.de/browse/OPS-3666
> OPs-3666-Change-confusing-sshd_banner-ionos-vms

- roles/cronjob_s3_backup/tasks/main.yml
https://ticketsystem.dbildungscloud.de/browse/OPS-3571
> OPS-3571-backup-for-bbbas-s3-buckets-that-saves-tf-state-file

- roles/monitoring_bbb/tasks/main.yml
> OPS-3648 Moved BBB basic auth 1pw secret name to variable

- roles/collabora_installation/tasks/main.yml
https://ticketsystem.dbildungscloud.de/browse/OPS-3702
> OPS-3702-add collabora_installation role

- roles/monitoring_bbb/tasks/main.yml
> OPS-3648 Renamed bbb_new_exporters to bbb_ebbba_exporters

- roles/collabora_installation/tasks/main.yml
https://ticketsystem.dbildungscloud.de/browse/OPS-3812
> OPS-3812-Connect-Nextcloud-to-Collabora

- roles/monitoring_bbb/vars/main.yml
> OPS-3798 Fixed TURN exporter lists

- roles/kubernetes_prometheus/tasks/prometheus.yml
> OPS-3285 Added Grafana PVC

- roles/collabora_installation/tasks/main.yml
While updating the domains which are allowed to access collabora, it was noticed that the ingress api version isnot supported anymore. Updated it. 
https://ticketsystem.dbildungscloud.de/browse/OPS-3853
> OPS-3853-update ingress api version

- roles/multi_instance_onepassword/tasks/multi-instance-onepassword.yml
> OPS-2040 Added loop_control label to multi instance 1Password

- roles/restore/tasks/duply.yml
- roles/restore/tasks/duply_configuration.yml
- roles/users/tasks/users.yml
> DBP-87-fix-onepassword-error

- roles/kubernetes_common/tasks/defaults/main.yml
- roles/kubernetes_common/tasks/kubernetes-event-exporter.yml
https://ticketsystem.dbildungscloud.de/browse/DBP-62
> DBP-62-create-vaults-and-transfer-secrets-to-dbp

- roles/monitoring_bbb/vars/main.yml
> DBP-78 Switched BBB exporter and node exporter ports

- roles/collabora_installation/tasks/main.yml
> OPS-4241 Added collabora_vault variable

- roles/kubernetes_maintenance/defaults/main.yml
- roles/kubernetes_maintenance/tasks/main.yml
- roles/kubernetes_maintenance/tasks/start.yml
- roles/kubernetes_maintenance/tasks/stop.yml
- roles/kubernetes_maintenance/templates/ingress-rules.yml.j2
- roles/kubernetes_maintenance/templates/maintenance.html.j2
> Dbp 69 maintenance mode

- roles/awx/kustomization.yaml
- roles/awx/templates/awx-operator.yml
> OPS-4296 update-awx-operator-to-1.1.4

- roles/monitoring_bbb/vars/main.yml
> OPS-4512-add-blackbox-exporter-target-for-bbb-bw-prod

- roles/monitoring_bbb_blackbox_exporter/defaults/main.yml
- roles/monitoring_bbb_blackbox_exporter/tasks/main.yml
> Ops 4549 add bbb server blackbox exporters

- roles/monitoring_bbb/defaults/main.yml
- roles/monitoring_bbb/tasks/main.yml
- roles/monitoring_bbb/vars/main.yml
- roles/monitoring_bbb_autoscaler/defaults/main.yml
- roles/monitoring_bbb_autoscaler/tasks/main.yml
- roles/monitoring_bbb_blackbox_exporter/defaults/main.yml
- roles/monitoring_bbb_blackbox_exporter/tasks/main.yml
- roles/monitoring_bbb_liveness_probe/defaults/main.yml
- roles/monitoring_bbb_liveness_probe/tasks/main.yml
- roles/monitoring_bbb_liveness_probe/vars/main.yml
Should only be merged once OPS-4618 has been merged in infra-schulcloud 
> Ops 4618 rollout bbb 2.6

- roles/restore/tasks/duply.yml
- roles/restore/tasks/duply_configuration.yml
- roles/users/tasks/users.yml
add session_shorthand to 1password lookups so the code runs smoothly when executed in AWX
https://ticketsystem.dbildungscloud.de/browse/OPS-4365
> OPS-4365-cycic-deployment-of-admin-cluster

- roles/cronjob_s3_backup/tasks/main.yml
> [OPS-4710] add exclude list to role for tf state backup

- roles/freeswitch/defaults/main.yml
- roles/freeswitch/files/freeswitch.service
- roles/freeswitch/tasks/main.yml
> OPS-4238 Role to install Freeswitch from sources

- roles/scalelite_server/defaults/main.yml
- roles/scalelite_server/tasks/main.yml
> OPS-4618 Added role to add/remove BBB servers from Scalelite

- roles/postgres_config/defaults/main.yml
- roles/postgres_config/files/config-script.sh
- roles/postgres_config/handlers/main.yml
- roles/postgres_config/tasks/main.yml
- roles/postgres_config/templates/config-script.sh.j2
- roles/postgres_config/templates/secret.yml.j2
Add role to configure a PostgreSQL database:
- create new database
- add users with configurable password and privileges
- optional custom database command
[DBP-180](https://ticketsystem.dbildungscloud.de/browse/DBP-180)
> DBP-180-postgres-config-role

- roles/haproxy/tasks/firewall.yml
imrpve the haproxy - firewalld tasks 
firewalld has to be installed and running. If is no running the ansible tasks logs a message that does not make clear that the status has to be active. Now it gets checked if it is running - which makes debugging easier
> OPS-4367-new-infra-dev-servicecenter

- roles/lvm/defaults/main.yml
- roles/lvm/tasks/main.yml
> OPS-4924 Created LVM Ansible role

- roles/squid_proxy/tasks/main.yml
Omit password if user is not allowed on the proxy
(With the switch to different credentials for each stage, it's now possible that there is no password available for a user on a specific stage if he is not allowed there)
> OPS-4617-proxy-omit-password-when-user-absent

- roles/cronjob_s3_backup/tasks/main.yml
- roles/get_ionos_kubeconfig/tasks/main.yml
> Ops 4946 make check mode work on awx

- roles/cassandra/tasks/main.yml
> OPS-4987 Use fullnameOverride for Cassandra

- roles/blackbox_exporter/tasks/main.yml
- roles/cassandra/tasks/main.yml
- roles/kubernetes_common/tasks/fluentbit.yml
- roles/kubernetes_common/tasks/ingress.yml
- roles/kubernetes_common/tasks/kubernetes-event-exporter.yml
- roles/kubernetes_common/tasks/nfs-provider.yml
- roles/kubernetes_common/tasks/otc-cert-manager.yml
- roles/kubernetes_maintenance/tasks/start.yml
- roles/kubernetes_monitoring/tasks/main.yml
- roles/kubernetes_prometheus/tasks/main.yml
- roles/loki/tasks/main.yml
- roles/onepassword/tasks/main.yml
- roles/trivy_operator/tasks/main.yml
- roles/victoriametrics/tasks/main.yml
> OPS-4990-display-adding-helm-repo-as-not-changed

- roles/get_ionos_kubeconfig/tasks/main.yml
Add newline between the certificates (the CA of sc-prod-legacy does not end with one)
> OPS-4617-fix-newline-for-prod-legacy

- roles/squid_proxy/files/custom_squid.conf
- roles/squid_proxy/handlers/main.yml
- roles/squid_proxy/tasks/main.yml
- roles/squid_proxy/templates/custom_squid.local.j2
Add fail2ban filter for squid.
[OPS-4619](https://ticketsystem.dbildungscloud.de/browse/OPS-4619)
> OPS-4619-squid-fail2ban

- roles/get_ionos_kubeconfig/tasks/main.yml
Fix proxy_domain check (switched to empty string instead of omit).
Merge with PR in infra-schulcloud.
[OPS-5025](https://ticketsystem.dbildungscloud.de/browse/OPS-5025)
https://github.com/hpi-schul-cloud/infra-schulcloud/pull/686
> OPS-5025-fix-proxy-domain-defined-check

- roles/squid_proxy/tasks/main.yml
- roles/squid_proxy/templates/bash_script.j2
[OPS-5068](https://ticketsystem.dbildungscloud.de/browse/OPS-5068)
> OPS-5068-reload-squid-after-cert-renewal

- roles/freeswitch/tasks/main.yml
> DBP-244 Remove creates

- roles/add_partition/defaults/main.yml
- roles/add_partition/tasks/main.yml
- roles/postgres_config/tasks/main.yml
Add a role that creates a simple partition and mounts it to per default to the /data dir
> OPS-4953-create-partition-role

- plugins/modules/LICENSE-APACHE2.txt
- plugins/modules/detect_pacemaker_cluster.py
- plugins/modules/pcs_auth.py
- plugins/modules/pcs_cluster.py
- plugins/modules/pcs_constraint_colocation.py
- plugins/modules/pcs_constraint_location.py
- plugins/modules/pcs_constraint_order.py
- plugins/modules/pcs_property.py
- plugins/modules/pcs_quorum_qdevice.py
- plugins/modules/pcs_resource.py
- plugins/modules/pcs_resource_defaults.py
- plugins/modules/pcs_stonith_level.py
- roles/squid_proxy_ha/defaults/main.yml
- roles/squid_proxy_ha/files/custom_squid.conf
- roles/squid_proxy_ha/files/ha-cluster-exporter.service
- roles/squid_proxy_ha/handlers/main.yml
- roles/squid_proxy_ha/tasks/certificate.yml
- roles/squid_proxy_ha/tasks/hacluster.yml
- roles/squid_proxy_ha/tasks/main.yml
- roles/squid_proxy_ha/tasks/monitoring.yml
- roles/squid_proxy_ha/tasks/prepare.yml
- roles/squid_proxy_ha/tasks/proxy.yml
- roles/squid_proxy_ha/templates/custom_squid.local.j2
- roles/squid_proxy_ha/templates/ha_cluster_exporter.web.yaml.j2
- roles/squid_proxy_ha/templates/squid.conf.j2
Added HA Squid role and the necessary pcs modules.
[OPS-5012](https://ticketsystem.dbildungscloud.de/browse/OPS-5012)
https://github.com/hpi-schul-cloud/infra-schulcloud/pull/707
> OPS-5012-ha-kubernetes-proxy

- roles/resource_pool/defaults/main.yml
- roles/resource_pool/tasks/main.yml
> OPS-5162 Introduced terraform_workspace variable

- roles/freeswitch/tasks/main.yml
> OPS-4238 Removed not working Ansible task parameter

- roles/postgres_config/defaults/main.yml
- roles/postgres_config/tasks/main.yml
> Ops 5154 update postgres role

- .github/workflows/trigger-awx-on-push-to-master.yml
> OPS-5160 Trigger infra-dev rollout on push to master

- .github/workflows/trigger-awx-on-push-to-master.yml
> OPS-5162 Add concurrency group

- roles/squid_proxy_ha/tasks/prepare.yml
Add sorting of the proxy hosts to ensure proxy with lowest index is the main node.
> OPS-5438-fix-proxy-order

- roles/delete_nodepools/tasks/main.yml
> OPS-0000 Fix delete nodepools when Terraform outputs are missing

- roles/resource_pool/defaults/main.yml
- roles/resource_pool/tasks/main.yml
> Ops 5460 enable terraform complex vars

- roles/delete_nodepools/tasks/main.yml
> Ops 0000 fix delete nodepools when no terraform outputs

- roles/monitoring_bbb_liveness_probe/tasks/main.yml
> OPS-0000 Add proxy options to BBB liveness probes

- roles/victoriametrics_l/tasks/main.yml
- add role for victoriametrics longterm creation
> OPS-5748-victoriametrics-longtermstorage

- roles/monitoring_bbb/defaults/main.yml
- roles/monitoring_bbb/vars/main.yml
> DBP-395 Added job for autoscaler metrics

- roles/lvm/defaults/main.yml
- roles/lvm/tasks/main.yml
> OPS-5901-change-filesystem-for-schulcloud-devclusters

- roles/bettermarks_proxy/templates/apps.conf.j2
- roles/bettermarks_proxy/templates/school.conf.j2
Minimal changes to fix the bettermarks proxy:
- Additional block for media subdomain (provided by bettermarks)
- Replace domains in the location / block as well
- Replace acc subdomain coming through the apps proxy
> Minimal changes to fix bettermarks proxy

- roles/bettermarks_proxy/defaults/main.yml
- roles/bettermarks_proxy/templates/apm.conf.j2
- roles/bettermarks_proxy/templates/apps.conf.j2
- roles/bettermarks_proxy/templates/basic.conf.j2
- roles/bettermarks_proxy/templates/school.conf.j2
Add headers to all proxies. 
That way bettermarks can detect if a request comes from the proxy or a client.
[OPS-5945](https://ticketsystem.dbildungscloud.de/browse/OPS-5945)
> OPS-5945-add-header-to-bettermarks-proxy-requests

- roles/postgres_config/defaults/main.yml
- roles/postgres_config/tasks/main.yml
- change the length to allow for longer database names
> DBP-680-shorten-name-of-postgres-job

- roles/basic/tasks/basic_install_ubuntu.yml
> DBP-684 Uninstall fwupd as part of the basic role

- roles/lvm/tasks/main.yml
> OPS-6197 Resize LV

- roles/cassandra/tasks/main.yml
> Ops 5829 cassandra cleanup

- roles/delete_nodepools/tasks/main.yml
- roles/get_ionos_kubeconfig/tasks/main.yml
- roles/resource_pool/tasks/main.yml
> Ops-6230-switch-to-ionos-token-auth

- roles/get_ionos_kubeconfig/tasks/main.yml
- roles/multi_instance_onepassword/tasks/multi-instance-onepassword.yml
- roles/onepassword/tasks/main.yml
- roles/resource_pool/tasks/main.yml
- roles/restore/tasks/duply.yml
- roles/restore/tasks/duply_configuration.yml
- roles/users/tasks/users.yml
Refactor all occurences of dbildungscloud.onepwd module to use new variable op_credentials for authentication rather than relying on env variables.
This is designed to be backwards compatible, as the variables will still be sourced from environment if no var is provided explicitly
[Successful run using extra_vars](https://awx.dbildungscloud.de/#/jobs/playbook/19131/output)
[Successful run using env_vars](https://awx.dbildungscloud.de/#/jobs/playbook/19145/output)
[Almost successful check on prod using env_vars](https://awx.dbildungscloud.de/#/jobs/playbook/19150/output)
[OPS-6253](https://ticketsystem.dbildungscloud.de/browse/OPS-6253)
[Codependent PR](https://github.com/hpi-schul-cloud/infra-schulcloud/pull/1112)
> Notice: Please remove the WIP label if the PR is ready to review, …
> Ops 6253 awx logs sensitive data

- roles/privacyidea/defaults/main.yml
- roles/privacyidea/tasks/installation.yml
To control the installation of MariaDB, a conditional statement (when) is used, and a variable is defined that determines whether or not MariaDB should be installed.
The version of PrivacyIDEA to be installed is privacyidea_version: 3.8.1
> Dbp 814 install configure privacyidea spsh staging schulportal

- roles/cassandra/tasks/main.yml
Add `set -e` to the cleanup script to let it fail if one of the commands fails.
That way it will be restarted and we get an alert if it the problems stays.
[OPS-6533](https://ticketsystem.dbildungscloud.de/browse/OPS-6533)
> OPS-6533-fix-cassandra-cleanup-execution

- roles/privacyidea/defaults/main.yml
This pull request reverts the privacyidea_version from "3.8.1" back to "3.9.2-1jammy".
Reason for Reversion
The version "3.8.1" is not valid for our current setup and must be installed using the Python pip manager. This will be handled separately in ticket DBP-852.
Additional Information
For details on handling the installation of version "3.8.1" with the Python pip manager, please refer to ticket DBP-852.
> DBP-852-revert privacyidea version to  3.9.2-1jammy

- roles/bettermarks_proxy/defaults/main.yml
- roles/bettermarks_proxy/templates/apps.conf.j2
- roles/bettermarks_proxy/templates/basic.conf.j2
- roles/bettermarks_proxy/templates/school.conf.j2
Add CSP functionality for bettermarks proxy:
- Add proxy/subdomain for csp-reports
- If enabled: Add Content-Security-Policy-Report-Only header to report requests, that are not going through the proxy
[OPS-6579](https://ticketsystem.dbildungscloud.de/browse/OPS-6579)
> OPS-6579-bettermarks-proxy-csp

- roles/bettermarks_proxy/defaults/main.yml
- roles/bettermarks_proxy/templates/apps.conf.j2
- roles/bettermarks_proxy/templates/basic.conf.j2
- roles/bettermarks_proxy/templates/school.conf.j2
Add option to enforce CSP (as default) instead of just reporting it.
(Not enabled on prod yet).
[OPS-6579](https://ticketsystem.dbildungscloud.de/browse/OPS-6579)
> OPS-6579-bettermarks-proxy-cspenforce-option

- roles/bettermarks_proxy/templates/apps.conf.j2
- roles/bettermarks_proxy/templates/basic.conf.j2
- roles/bettermarks_proxy/templates/school.conf.j2
Add the instance domain itself (not just subdomains) to the CSP to fix blocked iframes.
> OPS-6579-bettermarks-proxy-csp-fix-iframe

- roles/delete_nodepools/tasks/main.yml
- roles/get_ionos_kubeconfig/tasks/main.yml
Changes for compatibility with ionoscloudsdk.ionoscloud 7.4.1.
https://github.com/hpi-schul-cloud/infra-schulcloud/pull/1177
https://github.com/dBildungsplattform/infra-dbp/pull/125
> OPS-6674-changes-ionoscloudsdk

- roles/basic/tasks/main.yml
- roles/users/tasks/main.yml
> DBP-929 added condition to run on debian

- .ansible-lint
- roles/tls_auth_certificates/defaults/main.yml
- roles/tls_auth_certificates/tasks/ca.yml
- roles/tls_auth_certificates/tasks/checks.yml
- roles/tls_auth_certificates/tasks/client-certificates.yml
- roles/tls_auth_certificates/tasks/crl.yml
- roles/tls_auth_certificates/tasks/main.yml
> OPS-6558 Automate TLS-auth client certificates

- roles/users/tasks/users.yml
> OPS-6846 Make user SSH key exclusive

- roles/syslog/tasks/setup-syslog.yml
> OPS-6989-removed duply task

- roles/privacyidea/defaults/main.yml
- roles/privacyidea/tasks/install_packages.yml
- roles/privacyidea/templates/privacyideaapp.py.j2
> DBP-928-fix

- roles/privacyidea_ha/defaults/main.yml
- roles/privacyidea_ha/handlers/main.yml
- roles/privacyidea_ha/tasks/configure_privacyidea.yml
- roles/privacyidea_ha/tasks/generate_keys.yml
Create public key file for subscription signature validation
> Create public key file for subscription signature validation

- roles/bettermarks_proxy/templates/helpdesk.conf.j2
Add configuration for the bettermarks helpdesk subdomain:
Uses the default configuration and
- replaces bettermarks.com with the proxy domain
- only allows access to
- /help
- /assets
- /api
[OPS-7205](https://ticketsystem.dbildungscloud.de/browse/OPS-7205)
> OPS-7205-bettermarks-helpdesk

- roles/privacyidea_ha/tasks/generate_keys.yml
Fix issue in Delete local copies task
> set ignore_errors

- roles/kubernetes_common/defaults/main.yml
- roles/kubernetes_common/tasks/main.yml
> DBP-1115 Make Fluent-bit optional

- roles/privacyidea_ha/templates/privacyidea-exporter.service.j2
fix: resolve issue where privacyidea-exporter/socket is not created after reboot
> fix issue :privacyidea-exporter folder is not created after reboot

- roles/awx/defaults/main.yml
- roles/awx/tasks/main.yml
> OPS-7622 Update AWX-Operator to latest version using Helm

- roles/freeswitch/defaults/main.yml
- roles/freeswitch/handlers/main.yml
- roles/freeswitch/tasks/main.yml
Switch from compiling on the machine itself to pre-compiled binaries.
Has to be merged together with the matching infra-schulcloud PR (https://github.com/hpi-schul-cloud/infra-schulcloud/pull/1391).
> DBP-769-freeswitch-use-binaries

- roles/monitoring_bbb/defaults/main.yml
- roles/monitoring_bbb/vars/main.yml
> DBP-1305 Add cAdvisor to Scalelite Monitoring

- roles/cloudprober/defaults/main.yml
Define probe for Servicecenter services via Ingress
> DBP-1276 Added Loki + Vmagent ingress probe

- roles/users/defaults/main.yml
- roles/users/tasks/users.yml
> DBP-0000 improve role

- roles/server_monitoring/defaults/main.yml
- roles/server_monitoring/tasks/main.yml
- roles/server_monitoring/templates/default.conf.j2
- roles/server_monitoring/templates/docker-compose.yml.j2
- roles/server_monitoring/templates/nginx.conf.j2
> OPS-7058 server_monitoring role

- roles/monitoring_bbb/defaults/main.yml
- roles/monitoring_bbb/vars/main.yml
Add postgreSQL exporter scrape
> DBP-1106_BBB_Postgres_Exporter

- roles/coturn/defaults/main.yml
- roles/coturn/handlers/main.yml
- roles/coturn/tasks/coturn.yml
- roles/coturn/tasks/fail2ban.yml
- roles/coturn/tasks/main.yml
- roles/coturn/tasks/ufw.yml
- roles/coturn/templates/docker-compose.yml.j2
- roles/coturn/templates/turnserver.conf.j2
- roles/server_monitoring/defaults/main.yml
- roles/server_monitoring/handlers/main.yml
- roles/server_monitoring/tasks/main.yml
> Dbp 1339 turn server role

- roles/scalelite/templates/docker-compose.yml.j2
Fixed health check for instances of greenlight.
> DBP-1306 Fix Greenlight Instance Health Check

- roles/wazuh_agent/defaults/main.yml
- roles/wazuh_agent/tasks/main.yml
Basic role to install the Wazuh agent on VMs.
Supports the [Additional security options](https://documentation.wazuh.com/current/user-manual/agent/agent-enrollment/security-options/index.html#additional-security-options) for agent enrollment.
[DBP-1374](https://ticketsystem.dbildungscloud.de/browse/DBP-1374)
> DBP-1374-wazuh-agent

- roles/privacyidea_ha/tasks/certificate.yml
> DBP-1385-tls-cert-renewal-0-fix post hook-privacyidea

- roles/kyverno/defaults/main.yml
- roles/kyverno/tasks/main.yml
> Ops 8387 admin kyverno docker token

- roles/scalelite/defaults/main.yml
- roles/scalelite/templates/docker-compose.yml.j2
- roles/server_monitoring/defaults/main.yml
Feste Hashes für installierte Artifakte
> DBP-1340-Feste Hashes für installierte Artifakte

- roles/scalelite/defaults/main.yml
> DBP-1340-image-hashes-fix

- roles/users/defaults/main.yml
- roles/users/tasks/users.yml
- roles/users/templates/autologout.sh.j2
Define timeout for shell to logout after beeing idle
> DBP-1412 shell idle autologout

- roles/users/defaults/main.yml
- roles/users/tasks/users.yml
- roles/users/templates/sshd_config.j2
make path to sshd config variable
> OPS-8800-empower-christopher-denicolo

- roles/users/tasks/users.yml
> OPS-8800 Correct module

- roles/multi_instance_onepassword/tasks/multi-instance-onepassword.yml
- roles/multi_instance_onepassword/templates/onepassword-operator-deployment.yml.j2
- roles/onepassword/default/main.yml
- roles/onepassword/tasks/main.yml
> Ops 8387 add docker token 1 pw operator

- roles/cassandra/tasks/main.yml
- roles/kubernetes_common/tasks/fluentbit.yml
- roles/kubernetes_monitoring/tasks/main.yml
- roles/kubernetes_prometheus/tasks/main.yml
- roles/kubernetes_prometheus/tasks/prometheus.yml
> Ops 8952 add docker token servicecenter

- roles/cloudprober/tasks/main.yml
> OPS-9044 Add session_shorthand
